name: DropParty
main: no.runsafe.dropparty.Plugin
version: 1.0.@BUILD@
author: Kruithne
description: Drop parties! Because RS2007 is win.
commands:
  dropparty:
    description: Drop-party related commands
    aliases: [dp]
